name: Build Workflow Job

on:
  workflow_call:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Use reusable Setup Steps
      id: setup-steps
      uses: ./.github/reusable-steps # To use this syntax we must have the repository checkout
      with:
        github_actor: ${{ github.actor }}
        access_token: ${{ secrets.TEST_ACCESS_TOKEN }}
    - name: Build with Maven
      run: mvn clean install --file pom.xml -DskipTests
