name: Sonar Workflow Job

on:
  workflow_call:

jobs:

  sonar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use reusable Setup Steps
      id: setup-steps
      uses: stchoupkoua/reusable-actions/setup-java-maven@main # To use this syntax we must have the repository checkout
      with:
        github_actor: ${{ github.actor }}
        access_token: ${{ secrets.TEST_ACCESS_TOKEN }}
    - name: Build with Maven
      run: mvn verify sonar:sonar -P sonarqube -Dsonar.token=${{ secrets.SONARCLOUD_TOKEN }} -Dsonar.projectKey=pipeline-demo
