name: Tests Workflow Job

on:
  workflow_call:
    inputs:
      filename:
        required: true
        type: string

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Use reusable Setup Steps
      uses: stchoupkoua/reusable-actions/setup-java-maven@main # To use this syntax we must have the repository checkout
      with:
        github_actor: ${{ github.actor }}
        access_token: ${{ secrets.TEST_ACCESS_TOKEN }}
    - name: Run Unit Tests
      run: mvn clean test -s ~/.m2/settings.xml -Dmaven.javadoc.skip=true
    - name: Upload artifact to enable deployment
      uses: actions/upload-artifact@v3
      with:
        name: tests result
        path: ${{ inputs.filename }}

  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Use reusable Setup Steps
      uses: stchoupkoua/reusable-actions/setup-java-maven@main # To use this syntax we must have the repository checkout
      with:
        github_actor: ${{ github.actor }}
        access_token: ${{ secrets.TEST_ACCESS_TOKEN }}
    - name: Run Integration Tests
      run: mvn verify -s ~/.m2/settings.xml -Dmaven.javadoc.skip=true
