name: Reusable Setup-Steps
description: Demonstrate how to use reusable steps in a workflow

runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Set up Maven settings.xml
      run: |
        mkdir -p ~/.m2
        echo "<settings>
                <servers>
                   <server>
                      <id>github-webank</id>
                      <username>${{ github.actor }}</username>
                      <password>${{ secrets.WEBANK_ACCESS_TOKEN }}</password>
                   </server>
                  </servers>
              </settings>" > ~/.m2/settings.xml
    - name: Run Unit and Integration Tests
      run: mvn verify -s ~/.m2/settings.xml -Dmaven.javadoc.skip=true
